platform :ios, '12.1'
use_frameworks!
inhibit_all_warnings!

def commomPods
  pod 'SwiftLint', "~>0.30.1"
  pod 'Kingfisher', "~>5.1"
  pod 'SwiftMessages', "~>6.0"
  pod 'Reachability', "~>3.2"
end

target 'BrewDog' do
  
  commomPods

  target 'BrewDogTests' do
    inherit! :complete
  end

  target 'BrewDogUITests' do
    inherit! :complete
  end
end
